"""Every API operation, mapped to exactly one permission key.

Generated from the live route table by `scripts/gen-authz-map.py`, then
hand-tuned; keep it in that order if you regenerate. Keys are endpoint
`module.function` names, which are unique across all 239 operations and — unlike
paths — carry no router prefix, so they survive a route being remounted.

`core.authz.assert_full_coverage()` runs at startup and refuses to boot if a
registered route is absent here. That assertion is what makes this file safe to
keep centrally: an endpoint added without a permission stops the app rather than
silently shipping unguarded.

PUBLIC        - no authentication (login, health)
AUTHENTICATED - any signed-in user, self-service only (their own profile,
                their own attendance, their own expenses)
"""

from core.authz_catalog import AUTHENTICATED, PUBLIC

ENDPOINT_PERMISSIONS: dict[str, str] = {
    "modules.ai_assistant.router.chat": "ai.create",  # POST /api/v1/ai/chat
    "modules.ai_assistant.router.chat_stream": "ai.create",  # POST /api/v1/ai/chat/stream
    "modules.ai_assistant.router.health": "ai.read",  # GET /api/v1/ai/health
    "modules.ai_assistant.router.trigger_ingest": "ai.create",  # POST /api/v1/ai/ingest
    "modules.ai_assistant.router.ingest_status": "ai.read",  # GET /api/v1/ai/ingest/status
    "modules.ai_assistant.router.list_sessions": "ai.read",  # GET /api/v1/ai/sessions
    "modules.ai_assistant.router.delete_session": "ai.delete",  # DELETE /api/v1/ai/sessions/{session_id}
    "modules.ai_assistant.router.get_session": "ai.read",  # GET /api/v1/ai/sessions/{session_id}
    "modules.assets.router.list_assets": "assets.read",  # GET /api/v1/assets/
    "modules.assets.router.create_asset": "assets.create",  # POST /api/v1/assets/
    "modules.assets.router.backfill_devices": "assets.backfill",  # POST /api/v1/assets/backfill-devices
    "modules.assets.router.list_categories": "assets.categories",  # GET /api/v1/assets/categories
    "modules.assets.router.create_category": "assets.categories",  # POST /api/v1/assets/categories
    "modules.assets.router.delete_category": "assets.categories",  # DELETE /api/v1/assets/categories/{category_id}
    "modules.assets.router.deployed": "assets.read",  # GET /api/v1/assets/deployed
    "modules.assets.router.lookup_by_code": "assets.read",  # GET /api/v1/assets/lookup/{code}
    "modules.assets.router.list_reports": "assets.reports",  # GET /api/v1/assets/reports
    "modules.assets.router.create_report": "assets.reports",  # POST /api/v1/assets/reports
    "modules.assets.router.update_report": "assets.reports",  # PUT /api/v1/assets/reports/{report_id}
    "modules.assets.router.delete_asset": "assets.delete",  # DELETE /api/v1/assets/{asset_id}
    "modules.assets.router.get_asset": "assets.read",  # GET /api/v1/assets/{asset_id}
    "modules.assets.router.update_asset": "assets.update",  # PUT /api/v1/assets/{asset_id}
    "modules.assets.router.get_asset_history": "assets.read",  # GET /api/v1/assets/{asset_id}/history
    "modules.attendance.router.log_day": "attendance.create",  # POST /api/v1/attendance
    "modules.attendance.router.team_board": "attendance.board",  # GET /api/v1/attendance/board
    "modules.attendance.router.adjust_comp_off": "attendance.adjust",  # POST /api/v1/attendance/comp-off/adjust
    "modules.attendance.router.comp_off_balance": "attendance.compoff",  # GET /api/v1/attendance/comp-off/{person_id}
    "modules.attendance.router.comp_off_ledger": "attendance.compoff",  # GET /api/v1/attendance/comp-off/{person_id}/ledger
    "modules.attendance.router.my_days": AUTHENTICATED,  # GET /api/v1/attendance/me
    "modules.attendance.router.my_comp_off": AUTHENTICATED,  # GET /api/v1/attendance/me/comp-off
    "modules.attendance.router.my_summary": AUTHENTICATED,  # GET /api/v1/attendance/me/summary
    "modules.attendance.router.person_days": "attendance.read",  # GET /api/v1/attendance/person/{person_id}
    "modules.attendance.router.person_summary": "attendance.read",  # GET /api/v1/attendance/person/{person_id}/summary
    "modules.attendance.router.delete_day": "attendance.delete",  # DELETE /api/v1/attendance/{entry_id}
    "modules.attendance.router.update_day": "attendance.update",  # PUT /api/v1/attendance/{entry_id}
    "modules.audit_trail.router.get_audit_list": "audit.read",  # GET /api/v1/audit/
    "modules.audit_trail.router.get_entity_audit_trail": "audit.read",  # GET /api/v1/audit/entity/{entity_type}/{entity_id}
    "modules.audit_trail.router.get_audit_statistics": "audit.read",  # GET /api/v1/audit/stats
    "modules.audit_trail.router.get_user_audit_trail": "audit.read",  # GET /api/v1/audit/user/{user_id}
    "modules.audit_trail.router.revert_audit_entry": "audit.revert",  # POST /api/v1/audit/{audit_id}/revert
    "modules.auth.router.clerk_login": PUBLIC,  # POST /api/v1/auth/clerk
    "modules.auth.router.clerk_config": PUBLIC,  # GET /api/v1/auth/clerk/config
    "modules.auth.router.google_login": PUBLIC,  # POST /api/v1/auth/google
    "modules.auth.router.login": PUBLIC,  # POST /api/v1/auth/login
    "modules.auth.router.me": AUTHENTICATED,  # GET /api/v1/auth/me
    "modules.auth.router.update_me": AUTHENTICATED,  # PUT /api/v1/auth/me
    "modules.auth.router.change_password": AUTHENTICATED,  # PUT /api/v1/auth/me/password
    "modules.auth.router.register": PUBLIC,  # POST /api/v1/auth/register
    "modules.auth.router.list_users": "users.read",  # GET /api/v1/auth/users
    "modules.auth.router.list_users_basic": "users.read",  # GET /api/v1/auth/users/basic
    "modules.auth.router.list_pending_users": "users.read",  # GET /api/v1/auth/users/pending
    "modules.auth.router.delete_user": "users.delete",  # DELETE /api/v1/auth/users/{user_id}
    "modules.auth.router.get_user": "users.read",  # GET /api/v1/auth/users/{user_id}
    "modules.auth.router.update_user": "users.update",  # PUT /api/v1/auth/users/{user_id}
    "modules.auth.router.approve_user": "users.approve",  # POST /api/v1/auth/users/{user_id}/approve
    "modules.auth.router.get_user_permissions": "users.permissions.read",  # GET /api/v1/auth/users/{user_id}/permissions
    "modules.auth.router.set_user_permissions": "users.permissions.manage",  # PUT /api/v1/auth/users/{user_id}/permissions
    "modules.backup.router.export_csv": "backup.export",  # POST /api/v1/backup/export/csv
    "modules.backup.router.export_xlsx": "backup.export",  # POST /api/v1/backup/export/xlsx
    "modules.backup.router.import_csv": "backup.import",  # POST /api/v1/backup/import/csv
    "modules.backup.router.import_xlsx": "backup.import",  # POST /api/v1/backup/import/xlsx
    "modules.backup.router.create_backup": "backup.create",  # POST /api/v1/backup/pg-dump
    "modules.backup.router.download_backup": "backup.read",  # GET /api/v1/backup/pg-dump/download/{filename}
    "modules.backup.router.backup_history": "backup.read",  # GET /api/v1/backup/pg-dump/history
    "modules.backup.router.restore_backup": "backup.restore",  # POST /api/v1/backup/pg-dump/restore
    "modules.backup.router.delete_backup_file": "backup.delete",  # DELETE /api/v1/backup/pg-dump/{filename}
    "modules.backup.router.table_counts": "backup.read",  # GET /api/v1/backup/table-counts
    "modules.comparison.router.compare_couples_endpoint": "comparison.read",  # POST /api/v1/comparison/couples
    "modules.comparison.router.compare_devices_endpoint": "comparison.read",  # POST /api/v1/comparison/devices
    "modules.comparison.router.compare_pairs_endpoint": "comparison.read",  # POST /api/v1/comparison/pairs
    "modules.couples.router.list_couples": "couples.read",  # GET /api/v1/couples/
    "modules.couples.router.create_couple": "couples.create",  # POST /api/v1/couples/
    "modules.couples.router.get_map_data": "couples.read",  # GET /api/v1/couples/map-data
    "modules.couples.router.seed_couples": "couples.seed",  # POST /api/v1/couples/seed
    "modules.couples.router.delete_couple": "couples.delete",  # DELETE /api/v1/couples/{id}
    "modules.couples.router.get_couple": "couples.read",  # GET /api/v1/couples/{id}
    "modules.couples.router.update_couple": "couples.update",  # PUT /api/v1/couples/{id}
    "modules.couples.router.change_location": "couples.update",  # PUT /api/v1/couples/{id}/location
    "modules.couples.router.get_location_history": "couples.read",  # GET /api/v1/couples/{id}/location-history
    "modules.dashboard.router.device_type_breakdown": "dashboard.read",  # GET /api/v1/dashboard/device-type-breakdown
    "modules.dashboard.router.error_trends": "dashboard.read",  # GET /api/v1/dashboard/error-trends
    "modules.dashboard.router.home_summary": "dashboard.read",  # GET /api/v1/dashboard/home
    "modules.dashboard.router.pair_status": "dashboard.read",  # GET /api/v1/dashboard/pair-status
    "modules.dashboard.router.recent_activity": "dashboard.read",  # GET /api/v1/dashboard/recent-activity
    "modules.dashboard.router.dashboard_stats": "dashboard.read",  # GET /api/v1/dashboard/stats
    "modules.dashboard.router.status_distribution": "dashboard.read",  # GET /api/v1/dashboard/status-distribution
    "modules.devices.router.list_devices": "devices.read",  # GET /api/v1/devices/
    "modules.devices.router.create_device": "devices.create",  # POST /api/v1/devices/
    "modules.devices.router.seed_devices": "devices.seed",  # POST /api/v1/devices/seed
    "modules.devices.router.find_by_serial": "devices.read",  # GET /api/v1/devices/serial/{serial_number}
    "modules.devices.router.device_stats": "devices.read",  # GET /api/v1/devices/stats
    "modules.devices.router.delete_device": "devices.delete",  # DELETE /api/v1/devices/{id}
    "modules.devices.router.get_device": "devices.read",  # GET /api/v1/devices/{id}
    "modules.devices.router.update_device": "devices.update",  # PUT /api/v1/devices/{id}
    "modules.devices.router.change_status": "devices.update",  # PUT /api/v1/devices/{id}/status
    "modules.devices.router.get_status_history": "devices.read",  # GET /api/v1/devices/{id}/status-history
    "modules.documents.router.list_documents": "documents.read",  # GET /api/v1/documents/
    "modules.documents.router.list_by_entity": "documents.read",  # GET /api/v1/documents/by-entity/{entity_type}/{entity_id}
    "modules.documents.router.download_shared": "documents.read",  # GET /api/v1/documents/shared/{token}
    "modules.documents.router.upload_document": "documents.create",  # POST /api/v1/documents/upload
    "modules.documents.router.delete_document": "documents.delete",  # DELETE /api/v1/documents/{document_id}
    "modules.documents.router.get_document": "documents.read",  # GET /api/v1/documents/{document_id}
    "modules.documents.router.download_document": "documents.read",  # GET /api/v1/documents/{document_id}/download
    "modules.documents.router.create_share_link": "documents.share",  # POST /api/v1/documents/{document_id}/share-link
    "modules.downloads.router.list_items": "downloads.read",  # GET /api/v1/downloads/
    "modules.downloads.router.list_categories": "downloads.categories",  # GET /api/v1/downloads/categories
    "modules.downloads.router.create_category": "downloads.categories",  # POST /api/v1/downloads/categories
    "modules.downloads.router.delete_category": "downloads.categories",  # DELETE /api/v1/downloads/categories/{category_id}
    "modules.downloads.router.upload": "downloads.create",  # POST /api/v1/downloads/upload
    "modules.downloads.router.download_version": "downloads.read",  # GET /api/v1/downloads/versions/{version_id}/download
    "modules.downloads.router.delete_item": "downloads.delete",  # DELETE /api/v1/downloads/{item_id}
    "modules.downloads.router.get_item": "downloads.read",  # GET /api/v1/downloads/{item_id}
    "modules.downloads.router.update_item": "downloads.update",  # PUT /api/v1/downloads/{item_id}
    "modules.finance.router.list_expenses": "finance.read",  # GET /api/v1/finance/
    "modules.finance.router.create_expense": "finance.create",  # POST /api/v1/finance/
    "modules.finance.router.list_advances": "finance.read",  # GET /api/v1/finance/advances
    "modules.finance.router.create_advance": "finance.advances",  # POST /api/v1/finance/advances
    "modules.finance.router.delete_advance": "finance.advances",  # DELETE /api/v1/finance/advances/{advance_id}
    "modules.finance.router.get_balance": "finance.read",  # GET /api/v1/finance/balance/{person_id}
    "modules.finance.router.list_batches": "finance.read",  # GET /api/v1/finance/batches
    "modules.finance.router.create_batch": "finance.create",  # POST /api/v1/finance/batches
    "modules.finance.router.generate_bill": "finance.export",  # GET /api/v1/finance/bill.pdf
    "modules.finance.router.list_claims": "finance.read",  # GET /api/v1/finance/claims
    "modules.finance.router.create_claim": "finance.claims",  # POST /api/v1/finance/claims
    "modules.finance.router.update_claim": "finance.claims",  # PUT /api/v1/finance/claims/{claim_id}
    "modules.finance.router.settle_claim": "finance.settle",  # POST /api/v1/finance/claims/{claim_id}/settle
    "modules.finance.router.submit_claim": "finance.claims",  # POST /api/v1/finance/claims/{claim_id}/submit
    "modules.finance.router.export_expenses": "finance.export",  # GET /api/v1/finance/export
    "modules.finance.router.import_sheet": "finance.import",  # POST /api/v1/finance/import
    "modules.finance.router.my_finance": AUTHENTICATED,  # GET /api/v1/finance/my
    "modules.finance.router.settlement": "finance.settle",  # GET /api/v1/finance/settlement
    "modules.finance.router.get_summary": "finance.summary",  # GET /api/v1/finance/summary
    "modules.finance.router.delete_expense": "finance.delete",  # DELETE /api/v1/finance/{expense_id}
    "modules.finance.router.get_expense": "finance.read",  # GET /api/v1/finance/{expense_id}
    "modules.finance.router.update_expense": "finance.update",  # PUT /api/v1/finance/{expense_id}
    "modules.finance.router.set_expense_status": "finance.update",  # PUT /api/v1/finance/{expense_id}/status
    "main.health_check": PUBLIC,  # GET /api/v1/health
    "modules.inventory.router.list_materials": "materials.read",  # GET /api/v1/inventory/
    "modules.inventory.router.create_material": "materials.create",  # POST /api/v1/inventory/
    "modules.inventory.router.get_materials_by_couple": "materials.read",  # GET /api/v1/inventory/by-couple/{couple_id}
    "modules.inventory.router.copy_from_couple": "materials.create",  # POST /api/v1/inventory/copy-from/{source_couple_id}
    "modules.inventory.router.create_from_template": "materials.templates",  # POST /api/v1/inventory/from-template/{template_id}
    "modules.inventory.router.seed_inventory": "materials.seed",  # POST /api/v1/inventory/seed
    "modules.inventory.router.get_suggestions": "materials.read",  # GET /api/v1/inventory/suggestions
    "modules.inventory.router.list_templates": "materials.templates",  # GET /api/v1/inventory/templates
    "modules.inventory.router.create_template": "materials.templates",  # POST /api/v1/inventory/templates
    "modules.inventory.router.update_template": "materials.templates",  # PUT /api/v1/inventory/templates/{template_id}
    "modules.inventory.router.delete_material": "materials.delete",  # DELETE /api/v1/inventory/{material_id}
    "modules.inventory.router.get_material": "materials.read",  # GET /api/v1/inventory/{material_id}
    "modules.inventory.router.update_material": "materials.update",  # PUT /api/v1/inventory/{material_id}
    "modules.updates.router.leadership_summary": "leadership.read",  # GET /api/v1/leadership/summary
    "modules.locations.router.list_locations": "locations.read",  # GET /api/v1/locations/
    "modules.locations.router.create_location": "locations.create",  # POST /api/v1/locations/
    "modules.locations.router.all_location_history": "locations.read",  # GET /api/v1/locations/history
    "modules.locations.router.location_history_for_couple": "locations.read",  # GET /api/v1/locations/history/{couple_id}
    "modules.locations.router.get_location": "locations.read",  # GET /api/v1/locations/{id}
    "modules.locations.router.update_location": "locations.update",  # PUT /api/v1/locations/{id}
    "modules.pairs.router.list_pairs": "pairs.read",  # GET /api/v1/pairs/
    "modules.pairs.router.create_pair": "pairs.create",  # POST /api/v1/pairs/
    "modules.pairs.router.seed_pairs": "pairs.seed",  # POST /api/v1/pairs/seed
    "modules.pairs.router.get_pair_stats": "pairs.read",  # GET /api/v1/pairs/stats
    "modules.pairs.router.delete_pair": "pairs.delete",  # DELETE /api/v1/pairs/{pair_id}
    "modules.pairs.router.get_pair": "pairs.read",  # GET /api/v1/pairs/{pair_id}
    "modules.pairs.router.update_pair": "pairs.update",  # PUT /api/v1/pairs/{pair_id}
    "modules.personnel.router.list_personnel": "personnel.read",  # GET /api/v1/personnel/
    "modules.personnel.router.create_person": "personnel.create",  # POST /api/v1/personnel/
    "modules.personnel.router.backfill_links": "personnel.create",  # POST /api/v1/personnel/backfill-links
    "modules.personnel.router.search_personnel": "personnel.read",  # GET /api/v1/personnel/search
    "modules.personnel.router.seed_personnel": "personnel.seed",  # POST /api/v1/personnel/seed
    "modules.personnel.router.delete_person": "personnel.delete",  # DELETE /api/v1/personnel/{person_id}
    "modules.personnel.router.get_person": "personnel.read",  # GET /api/v1/personnel/{person_id}
    "modules.personnel.router.update_person": "personnel.update",  # PUT /api/v1/personnel/{person_id}
    "modules.personnel.router.get_person_assignments": "personnel.read",  # GET /api/v1/personnel/{person_id}/assignments
    "modules.personnel.router.link_user": "personnel.create",  # POST /api/v1/personnel/{person_id}/link-user
    "modules.projects.router.list_projects": "projects.read",  # GET /api/v1/projects/
    "modules.projects.router.create_project": "projects.create",  # POST /api/v1/projects/
    "modules.projects.router.deployments_for_entity": "projects.read",  # GET /api/v1/projects/deployments/for/{entity_type}/{entity_id}
    "modules.projects.router.update_movement_item": "projects.equipment",  # PUT /api/v1/projects/movements/items/{item_id}
    "modules.projects.router.update_phase": "projects.phases",  # PUT /api/v1/projects/phases/{phase_id}
    "modules.projects.router.delete_project": "projects.delete",  # DELETE /api/v1/projects/{project_id}
    "modules.projects.router.get_project": "projects.read",  # GET /api/v1/projects/{project_id}
    "modules.projects.router.update_project": "projects.update",  # PUT /api/v1/projects/{project_id}
    "modules.projects.router.close_project": "projects.close",  # POST /api/v1/projects/{project_id}/close
    "modules.projects.router.list_deployments": "projects.read",  # GET /api/v1/projects/{project_id}/deployments
    "modules.projects.router.add_deployment": "projects.deployments",  # POST /api/v1/projects/{project_id}/deployments
    "modules.projects.router.remove_deployment": "projects.deployments",  # DELETE /api/v1/projects/{project_id}/deployments/{deployment_id}
    "modules.projects.router.add_member": "projects.members",  # POST /api/v1/projects/{project_id}/members
    "modules.projects.router.remove_member": "projects.members",  # DELETE /api/v1/projects/{project_id}/members/{member_id}
    "modules.projects.router.move_member": "projects.members",  # POST /api/v1/projects/{project_id}/members/{member_id}/move
    "modules.projects.router.list_movements": "projects.read",  # GET /api/v1/projects/{project_id}/movements
    "modules.projects.router.create_movement": "projects.equipment",  # POST /api/v1/projects/{project_id}/movements
    "modules.projects.router.outward_execute": "projects.equipment",  # POST /api/v1/projects/{project_id}/outward
    "modules.projects.router.outward_preview": "projects.read",  # POST /api/v1/projects/{project_id}/outward/preview
    "modules.projects.router.list_phases": "projects.read",  # GET /api/v1/projects/{project_id}/phases
    "modules.projects.router.create_phase": "projects.phases",  # POST /api/v1/projects/{project_id}/phases
    "modules.projects.router.get_summary": "projects.read",  # GET /api/v1/projects/{project_id}/summary
    "modules.projects.router.list_timeline": "projects.read",  # GET /api/v1/projects/{project_id}/timeline
    "modules.projects.router.create_timeline_entry": "projects.update",  # POST /api/v1/projects/{project_id}/timeline
    "modules.reports.router.generate_report": "reports.generate",  # POST /api/v1/reports/generate
    "modules.reports.router.list_templates": "reports.read",  # GET /api/v1/reports/templates
    "modules.search.router.search_global": "search.read",  # GET /api/v1/search/global
    "modules.search.router.search_suggestions": "search.read",  # GET /api/v1/search/suggestions
    "modules.seeding.router.remove_seeded": "seeding.remove",  # DELETE /api/v1/seeding/
    "modules.seeding.router.adopt_existing": "seeding.run",  # POST /api/v1/seeding/adopt
    "modules.seeding.router.preview_adopt": "seeding.read",  # GET /api/v1/seeding/adopt/preview
    "modules.seeding.router.run_seed": "seeding.run",  # POST /api/v1/seeding/run
    "modules.seeding.router.get_seed_status": "seeding.read",  # GET /api/v1/seeding/status
    "modules.settings.router.list_settings": "settings.read",  # GET /api/v1/settings/
    "modules.settings.router.system_info": "settings.read",  # GET /api/v1/settings/system-info
    "modules.settings.router.list_users": "users.read",  # GET /api/v1/settings/users
    "modules.settings.router.create_user": "users.create",  # POST /api/v1/settings/users
    "modules.settings.router.delete_user": "users.delete",  # DELETE /api/v1/settings/users/{user_id}
    "modules.settings.router.update_user": "users.update",  # PUT /api/v1/settings/users/{user_id}
    "modules.settings.router.update_setting": "settings.update",  # PUT /api/v1/settings/{key}
    "modules.status.router.change_status": "status.change",  # POST /api/v1/status/change
    "modules.status.router.get_status_history": "status.read",  # GET /api/v1/status/history/{entity_type}/{entity_id}
    "modules.status.router.get_status_stats": "status.read",  # GET /api/v1/status/stats
    "modules.troubleshooting.router.list_errors": "troubleshooting.read",  # GET /api/v1/troubleshooting/
    "modules.troubleshooting.router.create_error": "troubleshooting.create",  # POST /api/v1/troubleshooting/
    "modules.troubleshooting.router.get_errors_by_couple": "troubleshooting.read",  # GET /api/v1/troubleshooting/by-couple/{couple_id}
    "modules.troubleshooting.router.get_errors_by_device": "troubleshooting.read",  # GET /api/v1/troubleshooting/by-device/{device_id}
    "modules.troubleshooting.router.get_errors_by_pair": "troubleshooting.read",  # GET /api/v1/troubleshooting/by-pair/{pair_id}
    "modules.troubleshooting.router.get_faulty_devices": "troubleshooting.read",  # GET /api/v1/troubleshooting/faulty-devices
    "modules.troubleshooting.router.seed_errors": "troubleshooting.seed",  # POST /api/v1/troubleshooting/seed
    "modules.troubleshooting.router.get_error_stats": "troubleshooting.read",  # GET /api/v1/troubleshooting/stats
    "modules.troubleshooting.router.delete_error": "troubleshooting.delete",  # DELETE /api/v1/troubleshooting/{error_id}
    "modules.troubleshooting.router.get_error": "troubleshooting.read",  # GET /api/v1/troubleshooting/{error_id}
    "modules.troubleshooting.router.update_error": "troubleshooting.update",  # PUT /api/v1/troubleshooting/{error_id}
    "modules.troubleshooting.router.resolve_error": "troubleshooting.resolve",  # PUT /api/v1/troubleshooting/{error_id}/resolve
    "modules.troubleshooting.router.add_step": "troubleshooting.create",  # POST /api/v1/troubleshooting/{error_id}/steps
    "modules.troubleshooting.router.update_step": "troubleshooting.update",  # PUT /api/v1/troubleshooting/{error_id}/steps/{step_id}
    "modules.updates.router.list_updates": "updates.read",  # GET /api/v1/updates
    "modules.updates.router.create_update": "updates.create",  # POST /api/v1/updates
    "modules.updates.router.delete_comment": "updates.comment",  # DELETE /api/v1/updates/comments/{comment_id}
    "modules.updates.router.my_updates": AUTHENTICATED,  # GET /api/v1/updates/mine
    "modules.updates.router.delete_update": "updates.delete",  # DELETE /api/v1/updates/{update_id}
    "modules.updates.router.get_update": "updates.read",  # GET /api/v1/updates/{update_id}
    "modules.updates.router.edit_update": "updates.update",  # PUT /api/v1/updates/{update_id}
    "modules.updates.router.add_comment": "updates.comment",  # POST /api/v1/updates/{update_id}/comments
    # --- access control (added with the fine-grained permission engine) -----
    "modules.authz.router.get_catalog": AUTHENTICATED,  # GET /api/v1/authz/catalog
    "modules.authz.router.list_roles": "users.read",  # GET /api/v1/authz/roles
    "modules.authz.router.create_role": "users.roles.manage",  # POST /api/v1/authz/roles
    "modules.authz.router.update_role": "users.roles.manage",  # PUT /api/v1/authz/roles/{role_id}
    "modules.authz.router.delete_role": "users.roles.manage",  # DELETE /api/v1/authz/roles/{role_id}
    "modules.authz.router.list_sessions": "users.sessions.read",  # GET /api/v1/authz/sessions
    "modules.authz.router.revoke_session": "users.sessions.revoke",  # DELETE /api/v1/authz/sessions/{session_id}
    "modules.authz.router.revoke_user_sessions": "users.sessions.revoke",  # POST /api/v1/authz/sessions/revoke-user/{id}
}
