"""create_missing_tables

Revision ID: abcbadeb3a5c
Revises: 6870e001deb7
Create Date: 2026-03-22 14:37:08.577253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abcbadeb3a5c'
down_revision: Union[str, None] = '6870e001deb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_history',
    sa.Column('couple_id', sa.UUID(), nullable=False),
    sa.Column('old_latitude', sa.Float(), nullable=False),
    sa.Column('old_longitude', sa.Float(), nullable=False),
    sa.Column('new_latitude', sa.Float(), nullable=False),
    sa.Column('new_longitude', sa.Float(), nullable=False),
    sa.Column('moved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('handled_by', sa.UUID(), nullable=True),
    sa.Column('had_rf', sa.Boolean(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('fitting_materials_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('configuration_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_history_couple_id'), 'location_history', ['couple_id'], unique=False)
    op.create_table('locations',
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coordinate', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('address_note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_locations_coordinate', 'locations', ['coordinate'], unique=False, postgresql_using='gist')
    op.create_table('couples',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pair_id', sa.UUID(), nullable=True),
    sa.Column('has_rf', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handling_person_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['handling_person_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couples')
    # op.drop_index('idx_locations_coordinate', table_name='locations', postgresql_using='gist')
    op.drop_table('locations')
    op.drop_index(op.f('ix_location_history_couple_id'), table_name='location_history')
    op.drop_table('location_history')
    # ### end Alembic commands ###