"""Partial unique index on serial_number

Revision ID: d419f6942c2f
Revises: abcbadeb3a5c
Create Date: 2026-03-22 22:23:01.763879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd419f6942c2f'
down_revision: Union[str, None] = 'abcbadeb3a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=False)
    op.create_index('ix_devices_serial_number_not_deleted', 'devices', ['serial_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_serial_number_not_deleted', table_name='devices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    # ### end Alembic commands ###